# Generated by Django 5.2.12 on 2026-03-11 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AppSetting",
            fields=[
                (
                    "key",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("value", models.TextField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "app_settings",
            },
        ),
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                (
                    "reddit_url",
                    models.URLField(
                        blank=True,
                        db_index=True,
                        max_length=500,
                        null=True,
                        unique=True,
                    ),
                ),
                ("text_content", models.TextField()),
                ("narration_text", models.TextField(blank=True, default="")),
                ("content_hash", models.CharField(db_index=True, max_length=64)),
                ("author", models.CharField(blank=True, default="", max_length=200)),
                (
                    "audio_file_path",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("part_count", models.PositiveIntegerField(default=1)),
                ("series_json", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "stories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StoryFolder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="folders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "story_folders",
            },
        ),
        migrations.CreateModel(
            name="StoryFolderMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "folder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stories.storyfolder",
                    ),
                ),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stories.story"
                    ),
                ),
            ],
            options={
                "db_table": "story_folder_memberships",
            },
        ),
        migrations.AddField(
            model_name="storyfolder",
            name="stories",
            field=models.ManyToManyField(
                related_name="folders",
                through="stories.StoryFolderMembership",
                to="stories.story",
            ),
        ),
        migrations.CreateModel(
            name="StoryView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("viewed_at", models.DateTimeField(auto_now=True)),
                ("hidden", models.BooleanField(default=False)),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        to="stories.story",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="story_views",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "story_views",
            },
        ),
        migrations.AddConstraint(
            model_name="storyfoldermembership",
            constraint=models.UniqueConstraint(
                fields=("folder", "story"), name="uq_folder_story"
            ),
        ),
        migrations.AddConstraint(
            model_name="storyfolder",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="uq_user_folder_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="storyview",
            constraint=models.UniqueConstraint(
                fields=("user", "story"), name="uq_user_story_view"
            ),
        ),
    ]
