# Generated by Django 5.2.12 on 2026-03-11 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NarrationScript",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "story",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="script",
                        to="stories.story",
                    ),
                ),
            ],
            options={
                "db_table": "narration_scripts",
            },
        ),
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("voice_profile", models.TextField()),
                ("voice_id", models.CharField(blank=True, default="", max_length=100)),
                (
                    "script",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="characters",
                        to="audio.narrationscript",
                    ),
                ),
            ],
            options={
                "db_table": "characters",
            },
        ),
        migrations.CreateModel(
            name="ScriptSegment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("narration", "Narration"),
                            ("dialogue", "Dialogue"),
                            ("sfx", "Sound Effect"),
                            ("ambient", "Ambient"),
                            ("pause", "Pause"),
                        ],
                        max_length=20,
                    ),
                ),
                ("text", models.TextField(blank=True, default="")),
                ("tone", models.CharField(blank=True, default="", max_length=100)),
                ("description", models.TextField(blank=True, default="")),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("loop", models.BooleanField(default=False)),
                (
                    "character",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="audio.character",
                    ),
                ),
                (
                    "script",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments",
                        to="audio.narrationscript",
                    ),
                ),
            ],
            options={
                "db_table": "script_segments",
                "ordering": ["order"],
            },
        ),
        migrations.AddConstraint(
            model_name="character",
            constraint=models.UniqueConstraint(
                fields=("script", "name"), name="uq_script_character_name"
            ),
        ),
    ]
